---
- name: Install PostgreSQL on {{ ansible_distribution }}-{{ ansible_distribution_major_version }}
  include: postgresql_{{ ansible_pkg_mgr }}{{ ansible_distribution_major_version }}.yml
  tags: [db, postgresql]
